### ISSUE TITLE
audio-components: use konva.js for drawing on canvas

### ISSUE THREAD

**Issue by julianpoemp** [IPS-LMU/octra#115]
This will improve readability and maintainibility of the code and speeds up performance. Further it will be easier to create new components.

## TODO:
- [x] re-implement media-components module
- [x] simplify time units to SampleUnit
- [x] re-implement audio-player
- [x] re-implement 2D-Editor
- [x] re-implement Linear Editor
- [x] check setting boundaries in the text editor
- [x] re-implement shortcuts
- [x] check correctness of time units and segments
- [x] check user interaction events and logging
