### ISSUE TITLE
1.5.0 release checklist

### ISSUE THREAD

**Issue by julianpoemp** [IPS-LMU/octra#154]
## TODO

- [ ] retrieve guidelines and projectconfig via API from server
- [x] replace ng2-dragula with angular/cdk dragndrop
- [ ] add implementation of the "secondSegmentFast" theme
- [ ] need for a better way to implement custom modifications on the GUI related to a project

## Bug Fixes

- [ ] (login): sometimes start transcription button vanishes after dragndrop
- [x] (2D-editor): audio-viewer draws to much overlays
- [x] switching from local mode to online mode does not work (segments not initialized correctly)
- [x] (2D-editor): no asr selected - dialogue missed
- [x] comment section dissapears just before quitting OCTRA. Looks strange.
- [x] (help-tools): automatically redirect to login after data has been cleared
- [x] (text-editor): on initialization there is something empty space in text field
- [x] (2D-editor): sometimes audio signal is drawn not correctly (esp. when signal is 15s, and 5s each line)
- [x] (login): remove data from demo mode automatically
- [x] (online mode): retrieve next job does not work correctly (same session)
- [x] (online mode): prompttext is not visible
- [x] (2D-editor): transcr-editor some keys are blocked
- [x] transcript not cleared after switching between local and demo mode
- [x] (navbar) level dialogue closes after add/remove/duplicate
- [x] (levels): switching and saving between levels does not work
- [x] (audio-viewer): add Boundary on Segment removes transcript
- [x] (audio-player): after playback on boundary the playcursor jumps to second 0
- [x] (dictaphone-editor): after switching back to dictaphone-editor the transcript is empty
- [x] (shortcuts): shortcut combinations do not work 100%

## Improvements

- [ ] (octra-api): replace old API with new [OCTRA-API](https://github.com/IPS-LMU/octra-backend/tree/main/apps/octra-api) 
- [x] move from momentjs to luxon
- [x] allow to switch between modes without loosing progress
- [x] (material design): upgrade to newer material package, but keep Bootstrap 4 and jquery because of summernote editor
- [x] (audio-viewer): save new boundary position after moving stopped
- [x] ~(audio-viewer): create separate function for creating boundary objects for konva~
- [x] (audio-viewer): check overlay drawing is limited to limited lines and drawing only when necessary
- [x] replace summernote with jodit

### Check editors

- [ ] Test all functionalities of Dictaphone-Editor
- [ ] -> Check splitting segments via text editor
- [ ] Test all functionalities of Linear-Editor
- [ ] Test all functionalities of 2D-Editor
- [ ] -> Check splitting segments via text editor
- [ ] Test all functionalities of TRN-Editor

### Check settings

- [ ] Check easy mode
- [ ] Check playback on hover
- [ ] Check follow playcursor option
- [ ] Check logging enable/disable
- [ ] Check loupe on/off

### Check tools

- [ ] Check exports
- [ ] Check audio cutting
- [ ] Check combine phrases
- [ ] Check ASR features

### Check modals

- [ ] Check overview modal

### Check logging

- [ ] Check logging in demo mode
- [ ] Check logging in local mode 
- [ ] Check logging in online mode

### Check modes

- [ ] Check demo mode
- [ ] Check local mode
- [ ] Check url mode
- [ ] Check online mode
- [ ] -> check if text promptext import works
- [ ] -> check if json/praat promptext import works
- [ ] -> check if server transcript import works
- [ ] -> check if server comment works
- [ ] -> check if server logtext works
